### ISSUE TITLE
AI player doesn't play a starter pokemon at game start

### ISSUE THREAD

**Issue by DrunkDutch** [DrunkDutch/comp-354#82]
AI player doesn't play a starter pokemon at game start, the game throws a null pointer exception after trying to query Froakie from the card database with the following stack trace:

Exception in thread "main" java.lang.NullPointerException
	at com.dmens.pokeno.player.Player.choosePokemonToEvolve(Player.java:346)
	at com.dmens.pokeno.player.Player.useCard(Player.java:381)
	at com.dmens.pokeno.player.AIPlayer.selectStarterPokemon(AIPlayer.java:71)
	at com.dmens.pokeno.controller.GameController.main(GameController.java:102)

**Comment by DrunkDutch** [comment]
Duplicate of #75 ,closing
